### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by rastislavcore** [hparra/gulp-spawn#19]
Got error while running
```
Error: spawn sass2less ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I try fix it with:
```
opts: { cwd: process.env.PATH },
```
and
```
opts: { env: { PATH: process.env.PATH } },
```
No luck.

🐐

**Comment by rastislavcore** [comment]
My bad. Bad command
